/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiyatro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CASPER
 */
public class oyun_ekle extends javax.swing.JFrame {

    /**
     * Creates new form oyun_ekle
     */
    private void UrunListeGuncelle(){
    
     try {
             String baslik[] = new String[]{"oyunturu", "oyunadi", "salon_no", "tarih", "ucret", "koltuk_sayisi", "Açıklama"};  
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/tiyatro", "root", "");
            
            st = con.createStatement();                
            rs = st.executeQuery("select * from oyunlar");
            rs.last();
           
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{  
                    
                    rs.getString("oyunturu"),  
                    rs.getString("oyunadi"),
                    rs.getString("salon_no"),
                    rs.getString("tarih"),  
                    rs.getString("ucret"),
                    rs.getString("koltuk_sayisi"),
                    rs.getString("aciklama"), 
                };
                i++;
            }
           
            con.close();
            table_urunler.setModel(new DefaultTableModel(data, baslik));
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
    }
    private static JFrame gelenform;
    public oyun_ekle() {
        
        super("Oyun Ekleme Formu");       
      
        initComponents();
        
        
        
        UrunListeGuncelle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ekle = new javax.swing.JButton();
        lbl_kategori = new javax.swing.JLabel();
        lbl_adi = new javax.swing.JLabel();
        lbl_renk = new javax.swing.JLabel();
        lbl_fiyat = new javax.swing.JLabel();
        txt_oyunturu = new javax.swing.JTextField();
        txt_ucret = new javax.swing.JTextField();
        txt_tarih = new javax.swing.JTextField();
        txt_adi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_urunler = new javax.swing.JTable();
        txt_guncelle = new javax.swing.JButton();
        txt_sil = new javax.swing.JButton();
        lbl_renk1 = new javax.swing.JLabel();
        txt_salon_no = new javax.swing.JTextField();
        lbl_fiyat1 = new javax.swing.JLabel();
        txt_koltuk_sayisi = new javax.swing.JTextField();
        lbl_fiyat2 = new javax.swing.JLabel();
        txt_aciklama = new javax.swing.JTextField();
        lbl_filtrele = new javax.swing.JLabel();
        txt_ara = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_ara = new javax.swing.JButton();
        btn_cikis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 650));
        setPreferredSize(new java.awt.Dimension(853, 560));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btn_ekle.setText("OYUN EKLE");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ekle);
        btn_ekle.setBounds(380, 310, 100, 23);

        lbl_kategori.setText("Oyun turu");
        getContentPane().add(lbl_kategori);
        lbl_kategori.setBounds(500, 160, 60, 14);

        lbl_adi.setText("Oyun Adi");
        getContentPane().add(lbl_adi);
        lbl_adi.setBounds(210, 130, 70, 20);

        lbl_renk.setText("Tarih");
        getContentPane().add(lbl_renk);
        lbl_renk.setBounds(210, 170, 60, 14);

        lbl_fiyat.setText("Ucret");
        getContentPane().add(lbl_fiyat);
        lbl_fiyat.setBounds(210, 210, 70, 14);

        txt_oyunturu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_oyunturuActionPerformed(evt);
            }
        });
        getContentPane().add(txt_oyunturu);
        txt_oyunturu.setBounds(580, 160, 170, 30);
        getContentPane().add(txt_ucret);
        txt_ucret.setBounds(280, 200, 170, 30);
        getContentPane().add(txt_tarih);
        txt_tarih.setBounds(280, 160, 170, 30);

        txt_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adiActionPerformed(evt);
            }
        });
        getContentPane().add(txt_adi);
        txt_adi.setBounds(280, 120, 170, 30);

        table_urunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_urunler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_urunlerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_urunler);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 380, 920, 220);

        txt_guncelle.setText("GÜNCELLE");
        txt_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_guncelleActionPerformed(evt);
            }
        });
        getContentPane().add(txt_guncelle);
        txt_guncelle.setBounds(610, 310, 100, 23);

        txt_sil.setText("SİL");
        txt_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_silActionPerformed(evt);
            }
        });
        getContentPane().add(txt_sil);
        txt_sil.setBounds(500, 310, 100, 23);

        lbl_renk1.setText("Salon No");
        getContentPane().add(lbl_renk1);
        lbl_renk1.setBounds(500, 200, 60, 14);
        getContentPane().add(txt_salon_no);
        txt_salon_no.setBounds(580, 200, 170, 30);

        lbl_fiyat1.setText("Koltuk Sayisi");
        getContentPane().add(lbl_fiyat1);
        lbl_fiyat1.setBounds(210, 250, 70, 14);
        getContentPane().add(txt_koltuk_sayisi);
        txt_koltuk_sayisi.setBounds(280, 240, 170, 30);

        lbl_fiyat2.setText("Açıklama");
        getContentPane().add(lbl_fiyat2);
        lbl_fiyat2.setBounds(500, 240, 60, 14);
        getContentPane().add(txt_aciklama);
        txt_aciklama.setBounds(580, 240, 170, 50);

        lbl_filtrele.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_filtrele.setText("Filtrele");
        getContentPane().add(lbl_filtrele);
        lbl_filtrele.setBounds(140, 350, 37, 17);

        txt_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_araActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ara);
        txt_ara.setBounds(180, 350, 170, 20);

        jButton1.setText("Geri Dön");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 100, 73, 23);

        jButton2.setText("Kapat");
        getContentPane().add(jButton2);
        jButton2.setBounds(650, 100, 61, 23);

        btn_ara.setText("Ara");
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ara);
        btn_ara.setBounds(350, 350, 49, 23);

        btn_cikis.setText("ÇIKIŞ");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cikis);
        btn_cikis.setBounds(270, 310, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiyatro/perde.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(850, 550));
        jLabel1.setPreferredSize(new java.awt.Dimension(850, 550));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -50, 920, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
                
            String oyunturu=txt_oyunturu.getText();
            String adi=txt_adi.getText();
            String salon_no=txt_salon_no.getText();
            String tarih=txt_tarih.getText();
            String ucret=txt_ucret.getText();
            String koltuk_sayisi=txt_koltuk_sayisi.getText();
            String aciklama=txt_aciklama.getText();
                
            try {
                    
                if (oyunturu.equals("") || adi.equals("") || tarih.equals("") || ucret.equals("")) {

                    JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");

                } else {            
                    Class.forName("com.mysql.jdbc.Driver");

                    Connection con = null;
                    Statement st = null;
                    ResultSet rs = null;
                    
                    con = DriverManager.getConnection("jdbc:mysql://localhost/tiyatro", "root", "");
                    st = con.createStatement();
                   
                    String oyunadi = null;
          
                    
                    String sql = "INSERT INTO oyunlar (oyunturu,oyunadi,salon_no,tarih,ucret,koltuk_sayisi,aciklama)" 
                            + " VALUES ('"+oyunturu+"', '"+oyunadi+"', '"+salon_no+"', '"+tarih+"', '"+ucret+"', '"+koltuk_sayisi+"', '"+aciklama+"')";

                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, adi + "  adlı oyun eklenmiştir.");
                    UrunListeGuncelle();
            
                }
            
            } catch (ClassNotFoundException ex) {
                 JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
            }  
            
            
        
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed
        
        String ara =txt_ara.getText();
        String baslik[] = new String[]{"oyunturu", "oyunadi", "salon_no", "tarih", "ucret", "koltuk_sayisi", "Açıklama"}; 

        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/tiyatro", "root", "");
            
            String sorgu ="select * from oyunlar where oyunadi like '%"+txt_ara.getText()+"%' or"
                    +" oyunturu like '%"+txt_ara.getText()+"%' or"
                    +" salon_no like '%"+txt_ara.getText()+"%' or"
                    +" tarih like '%"+txt_ara.getText()+"%' ";
            
            st = con.createStatement();
            rs = st.executeQuery(sorgu);
            
            rs.last();
           
            int say = rs.getRow();
            rs.beforeFirst();
 
            
            String sayi = null;                
            sayi = String.valueOf(rs.getRow());                

            if(say < 1){
                JOptionPane.showMessageDialog(null, "Aradığınız Oyun Bulunamadı!");
            }
            else{
                
                Object data[][] = new Object[say][];
                int i = 0;
                
                while (rs.next()) {

                    data[i] = new Object[]{ 
                        
                        rs.getString("oyunturu"),  
                        rs.getString("oyunadi"),
                        rs.getString("salon_no"),
                        rs.getString("tarih"),  
                        rs.getString("ucret"),
                        rs.getString("koltuk_sayisi"),
                        rs.getString("aciklama"),
                    };
                    i++;
                }
                table_urunler.setModel(new DefaultTableModel(data, baslik));
            }
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
        
    }//GEN-LAST:event_btn_araActionPerformed

    private void table_urunlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_urunlerMouseClicked
        
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement st1 =null;
        
        
        try {
        
            int row = table_urunler.getSelectedRow();
            int satir=row+1;
            String secim_yap=(table_urunler.getValueAt(row, 1).toString());
           
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/tiyatro", "root", "");
            
            String sorgu = "select * from oyunlar where id='"+satir+"'";
            //st = con.createStatement(); 
            st = con.createStatement();
            rs = st.executeQuery(sorgu);
            
            if(rs.last()){
                
                txt_oyunturu.setText(rs.getString("oyunturu"));
                txt_adi.setText(rs.getString("oyunadi"));
             txt_salon_no.setText(rs.getString("salon_no"));
                txt_tarih.setText(rs.getString("tarih"));
                txt_ucret.setText(rs.getString("ucret"));
                txt_koltuk_sayisi.setText(rs.getString("koltuk_sayisi"));
                txt_aciklama.setText(rs.getString("aciklama"));
            }
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }

    }//GEN-LAST:event_table_urunlerMouseClicked

    private void txt_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_guncelleActionPerformed
        
        try {
            
            int row = table_urunler.getSelectedRow();            
            String secim=(table_urunler.getValueAt(row, 0).toString());
            int satir=row+1;
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/tiyatro", "root", "");

            String sorgu = "UPDATE oyunlar SET oyunturu='"+txt_tur.getText()+"'"
                    +",oyunadi='"+txt_adi.getText()+"'"
                    +",salon_no='"+txt_salon_no.getText()+"'"
                    +",tarih='"+txt_tarih.getText()+"'"
                    +",ucret='"+txt_ucret.getText()+"'"
                    +",koltuk_sayisi='"+txt_koltuk_sayisi.getText()+"'"
                    +",aciklama='"+txt_aciklama.getText()+"' where id='"+satir+"'";
                    
          
            st = con.createStatement();
            st.executeUpdate(sorgu);

            JOptionPane.showMessageDialog(null, "Oyun  Güncellemesi Tamamlanmıştır.");

            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
        
        UrunListeGuncelle();
        
    }//GEN-LAST:event_txt_guncelleActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        
        oyun_ekle a = new oyun_ekle();
        a.setVisible(false);
        dispose();
        
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        
    }//GEN-LAST:event_formWindowClosing

    private void txt_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_silActionPerformed

            
        try {
            
            int row = table_urunler.getSelectedRow();            
            String secim=(table_urunler.getValueAt(row, 0).toString());
            int satir=row+1;
            
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/tiyatro", "root", "");

            String sorgu = "delete from oyunlar where id='"+satir+"'";
               
          
            st = con.createStatement();
            st.executeUpdate(sorgu);

            JOptionPane.showMessageDialog(null, "Oyun Başarıyla Silinmiştir");

            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
        
        UrunListeGuncelle();
        
    }//GEN-LAST:event_txt_silActionPerformed

    private void txt_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adiActionPerformed

    private void txt_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_araActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_araActionPerformed

    private void txt_oyunturuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_oyunturuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_oyunturuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     raporlar goster = new raporlar();
        goster.setVisible(true); 
        this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oyun_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oyun_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oyun_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oyun_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oyun_ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_adi;
    private javax.swing.JLabel lbl_filtrele;
    private javax.swing.JLabel lbl_fiyat;
    private javax.swing.JLabel lbl_fiyat1;
    private javax.swing.JLabel lbl_fiyat2;
    private javax.swing.JLabel lbl_kategori;
    private javax.swing.JLabel lbl_renk;
    private javax.swing.JLabel lbl_renk1;
    private javax.swing.JTable table_urunler;
    private javax.swing.JTextField txt_aciklama;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_ara;
    private javax.swing.JButton txt_guncelle;
    private javax.swing.JTextField txt_koltuk_sayisi;
    private javax.swing.JTextField txt_oyunturu;
    private javax.swing.JTextField txt_salon_no;
    private javax.swing.JButton txt_sil;
    private javax.swing.JTextField txt_tarih;
    private javax.swing.JTextField txt_ucret;
    // End of variables declaration//GEN-END:variables
}
