/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiyatro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CASPER
 */
public class raporlar extends javax.swing.JFrame {

    /**
     * Creates new form raporlar
     */
     
    
    public raporlar() {
        super("Rapor Ekranı");

        initComponents();
        
        String baslik[] = new String[]{"oyunturu", "oyunadi","ucret", "koltuk_sayisi", "Toplam Ücret" };  

        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = null;
            Statement st,st1 = null;
            ResultSet rs,rs1 = null;
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/tiyatro", "root", "");
            
            st = con.createStatement();
            st1 = con.createStatement();
            
            rs = st.executeQuery("select *, (ucret*koltuk_sayisi) as Toplam_ucret from vizyon_oyunlar");
            rs.last();
            
            int ali = Integer.parseInt(rs.getString("Toplam_ucret"));
            
           // alttaki 3 satırda raporlar formundak toplam tutarı ekrana yazdırdık
            rs1 = st1.executeQuery("select sum(ucret*koltuk_sayisi) as Toplamucret from vizyon_oyunlar");
            rs1.last();
            txt_toplam_tutar.setText(rs1.getString(1)+" TL");
            
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{  
                    
                    rs.getString("oyunturu"),  
                    rs.getString("oyunadi"), 
                    rs.getString("ucret"),
                    rs.getString("koltuk_sayisi"),
                    rs.getString("Toplam_ucret")
                };
                i++;
            }
            
            
            con.close();
            table_rapor.setModel(new DefaultTableModel(data, baslik));
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_satis = new javax.swing.JLabel();
        txt_toplam_tutar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_rapor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_cikis = new javax.swing.JButton();
        resim = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 700));
        getContentPane().setLayout(null);

        lbl_satis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_satis.setForeground(new java.awt.Color(255, 255, 255));
        lbl_satis.setText("Toplam Satış Tutarı");
        getContentPane().add(lbl_satis);
        lbl_satis.setBounds(30, 140, 200, 22);

        txt_toplam_tutar.setEnabled(false);
        getContentPane().add(txt_toplam_tutar);
        txt_toplam_tutar.setBounds(30, 170, 170, 30);

        table_rapor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_rapor);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 370, 740, 284);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RAPOR EKRANI");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 320, 30);
        jLabel1.getAccessibleContext().setAccessibleName("kullanici");

        jButton1.setText("OYUN EKLEME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 280, 151, 61);

        jButton2.setText("KULLANICI EKLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 280, 147, 61);

        jButton3.setText("Ana Sayfa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(580, 90, 90, 23);

        jButton4.setText("OYUN SATIŞ DETAYLARI");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 210, 180, 61);

        btn_cikis.setText("ÇIKIŞ");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cikis);
        btn_cikis.setBounds(579, 30, 80, 30);

        resim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiyatro/20121104142148-028cc6aa-me.jpg"))); // NOI18N
        getContentPane().add(resim);
        resim.setBounds(0, -80, 740, 540);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 40, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        oyun_ekle goster = new oyun_ekle();
        goster.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        uye_ekle goster = new uye_ekle();
        goster.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      vizyon_oyunlar goster = new vizyon_oyunlar();
        goster.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        
        raporlar kapat = new raporlar();
        kapat.setVisible(false);
        dispose();
        
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        uye_giris goster = new uye_giris();
        goster.setVisible(true); 
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new raporlar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_satis;
    private javax.swing.JLabel resim;
    private javax.swing.JTable table_rapor;
    private javax.swing.JTextField txt_toplam_tutar;
    // End of variables declaration//GEN-END:variables
}
