/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiyatro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author CASPER
 */
public class uye_ekle extends javax.swing.JFrame {

    /**
     * Creates new form uye_ekle
     */
    public uye_ekle() {
        
         super("Üye Ekle Formu");  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_kategori = new javax.swing.JLabel();
        lbl_kadi = new javax.swing.JLabel();
        lbl_parola = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_kategori = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_kadi = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_uye_ekle = new javax.swing.JButton();
        txt_parola = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btn_cikis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 900));
        getContentPane().setLayout(null);

        lbl_kategori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_kategori.setText("Kategori");
        getContentPane().add(lbl_kategori);
        lbl_kategori.setBounds(130, 250, 50, 17);

        lbl_kadi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_kadi.setText("Kullanıcı Adı");
        getContentPane().add(lbl_kadi);
        lbl_kadi.setBounds(110, 300, 68, 17);

        lbl_parola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_parola.setText("Parola");
        getContentPane().add(lbl_parola);
        lbl_parola.setBounds(140, 350, 37, 17);

        lbl_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_email.setText("E-Posta");
        getContentPane().add(lbl_email);
        lbl_email.setBounds(140, 410, 47, 17);

        txt_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kategoriActionPerformed(evt);
            }
        });
        getContentPane().add(txt_kategori);
        txt_kategori.setBounds(210, 240, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("ÜYE EKLEME FORMU");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 410, 100);
        getContentPane().add(txt_kadi);
        txt_kadi.setBounds(210, 290, 170, 30);
        getContentPane().add(txt_email);
        txt_email.setBounds(210, 400, 170, 30);

        btn_uye_ekle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_uye_ekle.setText("Kaydet");
        btn_uye_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uye_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_uye_ekle);
        btn_uye_ekle.setBounds(60, 470, 170, 30);
        getContentPane().add(txt_parola);
        txt_parola.setBounds(210, 340, 170, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Geri Dön");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 470, 140, 30);

        btn_cikis.setText("ÇIKIŞ");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cikis);
        btn_cikis.setBounds(650, 20, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiyatro/charlie-chaplin-clown.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-260, 0, 1010, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_uye_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uye_ekleActionPerformed
        
            String kategori=txt_kategori.getText();
            String kadi=txt_kadi.getText();
            String parola=txt_parola.getText();
            String email=txt_email.getText();
                
            try {
                    
                if (kategori.equals("") || kadi.equals("") || parola.equals("") || email.equals("")) {

                    JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");

                } else {            
                    Class.forName("com.mysql.jdbc.Driver");

                    Connection con = null;
                    Statement st = null;
                    ResultSet rs = null;
                    
                    con = DriverManager.getConnection("jdbc:mysql://localhost/tiyatro", "root", "");
                    st = con.createStatement();
                    
                    String sql = "INSERT INTO uyeler (kategori,kadi,parola,email)" 
                            + " VALUES ('"+kategori+"', '"+kadi+"', '"+parola+"', '"+email+"')";

                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Hoşgeldiniz " + kadi);
            
                }
            
            } catch (ClassNotFoundException ex) {
                 JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
            }  
        
    }//GEN-LAST:event_btn_uye_ekleActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed

        raporlar kapat = new raporlar();
        kapat.setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void txt_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kategoriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        raporlar goster = new raporlar();
        
        goster.setVisible(true); 
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uye_ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_uye_ekle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_kadi;
    private javax.swing.JLabel lbl_kategori;
    private javax.swing.JLabel lbl_parola;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_kadi;
    private javax.swing.JTextField txt_kategori;
    private javax.swing.JPasswordField txt_parola;
    // End of variables declaration//GEN-END:variables
}
